baseurl = "/490_590_2019/"
languageCode = "en-us"
title = "Geology 490/590 2019"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
# [[menu.main]]
#    name = "Reading"
#    url = "/reading/"
# [[menu.main]]
#    name = "Homeworks"
#    url = "homeworks"
# [[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/rstudio/blogdown"
# [[menu.main]]
#    name = "Twitter"
#    url = "https://twitter.com/rstudio"

[params]
    description = "Homepage for Drew Steen's GEOL 490/590 class"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "lab_logo_aidia_2016_xgC_icon.ico"

    [params.logo]
    url = "lab_logo_Aidia_2016.png"
    width = 50
    height = 50
    alt = "Logo"

